language: minimal

addons:
  apt:
    packages:
    - jq

script:
  - curl -fsSLo release.sh https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
  - chmod +x release.sh
  - ./release.sh
  - ./release.sh -s -p 0 -w 0
  - ./release.sh -g 1.13.5 -w 0
  - ./release.sh -s -g 1.13.5 -p 0 -w 0
